HW09_Fadeeva
kajigor/fl_2020_spbu_spr pull request #118
Opened 2020-04-20 12:51 UTC by rediska0123

Пока только 1 и 3.
В своем языке переделала функции (чтобы return был в конце) и добавила возможность ставить пробелы, переносы строки и табы.

2020-04-23 18:50 UTC, kajigor requested changes

2020-04-23 18:50 UTC, kajigor commented on LLang.md
> +* Допускается писать любое количество пробелов, знаков табуляции и/или переносов строки в любых местах, кроме позиций внутри ключевых слов `Def` и `Returns`. Например, допускается вообще не использов
А обещали, что можно писать пробелы где угодно: 

```
λ> runParser parseProg "Def func(x,y) {Read n;} Returns (n+x+y); {}"
Parsing succeeded!
Result:
func("x", "y") =
|_n := 0
|_read n
returns
+
|_+
| |_n
| |_x
|_y


Suffix:	InputStream {stream = "", curPos = Position {line = 0, col = 43}}
λ> runParser parseProg "Def func(x,y) {Re ad n;} Returns (n+x+y); {}"
Parsing failed
at position Position {line = 0, col = 0}:
	Expected "{"
```

2020-04-23 18:50 UTC, kajigor commented on src/Combinators.hs
> +incrPos (Position line col) '\t' = Position line (col + 4)
Табы ведут себя несколько иначе: 

```
λ> putStrLn "123\t56"
123 56
λ> runParser parseExpr "123\t56"     
Parsing succeeded!
Result:

123
Suffix:	InputStream {stream = "56", curPos = Position {line = 0, col = 7}}
λ> runParser parseExpr "1\t56"     
Parsing succeeded!
Result:

1
Suffix:	InputStream {stream = "56", curPos = Position {line = 0, col = 5}}
λ> putStrLn "1\t56"
1   56
```
Чтобы изменить в консоли размер таба на 4 пробела, достаточно сказать `tabs -4`

2020-04-23 18:51 UTC, kajigor commented
интерпретатор ок, табы надо поправить.

2020-04-23 19:15 UTC, rediska0123 commented
Поправила.
Я еще написала отчет (задание 2): Никите на новую версию языка (HW09), а Маше на старую (HW08). Мне тогда переделать это к следующей неделе, когда будет HW09?

2020-05-03 18:17 UTC, kajigor commented
У вас тесты не проходят.

```
      parseExpr:    FAIL
        test/Test/Expr.hs:112:
        expected: Parsing succeeded!
        Result:
        
        f()
        Suffix:	InputStream {stream = "", curPos = Position {line = 1, col = 6}}
         but got: Parsing succeeded!
        Result:
        
        f()
        Suffix:	InputStream {stream = "", curPos = Position {line = 1, col = 4}}
```

2020-05-03 18:20 UTC, kajigor commented
2 ок, табы ок.

2020-05-03 18:20 UTC, closed without merging