HW03 Шиманская Ольга
kajigor/fl_2020_spbu_spr pull request #29
Opened 2020-03-10 11:41 UTC by jeinygroove

2020-03-11 17:31 UTC, kajigor requested changes

2020-03-11 17:31 UTC, kajigor commented on src/Expr.hs
> +  in uberExpr [(mult, LeftAssoc), (div, LeftAssoc)] parser BinOp
А почему вдруг у умножения и деления разные приоритеты?

2020-03-11 17:31 UTC, kajigor commented on src/Expr.hs
> +  in uberExpr [(plus, RightAssoc), (minus, LeftAssoc)] parseMult BinOp
И тут тоже разные приоритеты. Сложение, кстати, лучше сделать левоассоцативным

2020-03-11 20:04 UTC, jeinygroove commented on src/Expr.hs
> +  in uberExpr [(mult, LeftAssoc), (div, LeftAssoc)] parser BinOp
одинаковые же, левоассоциативные

2020-03-11 20:05 UTC, jeinygroove commented on src/Expr.hs
> +  in uberExpr [(plus, RightAssoc), (minus, LeftAssoc)] parseMult BinOp
ой, наверное, опечаталась, левоассоциативное, конечно

2020-03-12 14:46 UTC, kajigor commented on src/Expr.hs
> +  in uberExpr [(mult, LeftAssoc), (div, LeftAssoc)] parser BinOp
Ассоциативность и приоритет -- разные вещи. Приоритет говорит о том, какие бинарные операции надо выполнять в первую очередь: умножение приоритетнее сложения, выражение 1 + 2 * 3 надо трактовать как 1 + (2 * 3). Ассоцитивность -- сначала вычислять левый операнд или правый: 1 - 2 - 3 трактуется, как (1 - 2) - 3, 1 ^ 2 ^ 3 -- как 1 ^ (2 ^ 3), потому что вычитание левоассоциативно, а возведение в степень -- правоассоциативно

2020-03-12 14:59 UTC, jeinygroove commented
@kajigor исправила

2020-03-13 13:20 UTC, kajigor commented
`parseExpr` ок

2020-03-13 13:20 UTC, closed without merging