done
kajigor/fl_2020_spbu_spr pull request #3
Opened 2020-02-19 19:11 UTC by ilyavoronin

2020-02-19 20:18 UTC, kajigor requested changes

2020-02-19 20:18 UTC, kajigor commented on src/Arith.hs
> +toPostfix (BinOp op a1 a2) = (toPostfix a1) ++ " " ++ (toPostfix a2) ++ " " ++ (case op of
У оператора реализован Show, лучше использовать его.

2020-02-19 20:18 UTC, kajigor commented on src/Arith.hs
> +                                  | isDigit x       = do {
parseNum завершится ошибкой, если первый символ не является цифрой. Парсеры уже выполняют роль валидаторов, лучше не делать дополнительных проверок. 

Например, этот код придется переписывать, если мы вдруг решим, что числа могут быть отрицательными (начинаться с -)

2020-02-19 20:18 UTC, kajigor commented on src/Arith.hs
> +                                  | (elem x "+*/-") = do {
Аналогично тут, проверка не нужна

2020-02-19 20:18 UTC, kajigor commented on src/Arith.hs
> +parseLbr :: String -> Maybe (Bool, String)
Имеющиеся сигнатуры менять нельзя

2020-02-19 20:18 UTC, kajigor commented on src/Arith.hs
> +parseLbr ('(':xs) = Just (True, xs)
Этим парсерам нет никакого смысла возвращать Bool. 
Если строка не начинается на скобку, парсер вернет Nothing, иначе -- Just ((), tail input). Корректный парсинг строки можно выразить без дополнительных булевых значений.

2020-02-19 20:18 UTC, kajigor commented on src/Arith.hs
> +parseTerm input = do
Тут немного ломается представление о том, что является термом. Терм это либо число, либо выражение в скобках. Тут логика про правую скобку оказывается где-то, где ей не положено быть. 
Тест на `parseTerm`: 

```
unit_parseTerm :: Assertion 
unit_parseTerm = do 
    parseTerm "(1" @?= Nothing

```

2020-02-20 10:58 UTC, ilyavoronin commented
@kajigor вроде бы все исправил

2020-02-20 15:09 UTC, kajigor commented
ok, зачтено

2020-02-20 15:09 UTC, kajigor approved these changes

2020-02-20 15:09 UTC, closed without merging