Gorbachev HW03
kajigor/fl_2020_spbu_spr pull request #34
Opened 2020-03-12 10:16 UTC by Peltorator

.

2020-03-13 13:24 UTC, kajigor requested changes

2020-03-13 13:24 UTC, kajigor commented on src/Expr.hs
> +parseExpr = uberExpr [(make '+' <|> make '-', LeftAssoc), (make '*' <|> make '/', LeftAssoc), (make '^', RightAssoc)]
Если вы добавили возведение в степень, то надо было еще и оператор в `Operator` добавить и `toOperator` переписать под это. Иначе получается так: 

```
λ> runParser parseExpr "1^2"
Success "^2" 
1
```

2020-03-13 13:39 UTC, Peltorator commented on src/Expr.hs
> +parseExpr = uberExpr [(make '+' <|> make '-', LeftAssoc), (make '*' <|> make '/', LeftAssoc), (make '^', RightAssoc)]
done

2020-03-13 13:39 UTC, Peltorator commented
done

2020-03-14 19:35 UTC, kajigor commented
ok

2020-03-14 19:35 UTC, closed without merging