HW03 Иван Олейник
kajigor/fl_2020_spbu_spr pull request #36
Opened 2020-03-12 13:51 UTC by ivanoleinik

2020-03-13 13:31 UTC, kajigor requested changes

2020-03-13 13:31 UTC, kajigor commented on src/Expr.hs
> +                     , (pow, RightAssoc)
Что-то где-то с возведением в степень не так. 
```
λ> runParser parseExpr "1^2"
Success "^2" 
1
```

2020-03-13 17:26 UTC, ivanoleinik commented on src/Expr.hs
> +                     , (pow, RightAssoc)
Исправил и добавил тесты

2020-03-14 19:38 UTC, kajigor commented
Ok

2020-03-14 19:38 UTC, closed without merging