HW03 Александра Новикова
kajigor/fl_2020_spbu_spr pull request #40
Opened 2020-03-12 15:06 UTC by AlyaNovikova

2020-03-13 13:35 UTC, kajigor requested changes

2020-03-13 13:35 UTC, kajigor commented on src/Expr.hs
> +            t <- term
Тут последний терм парсится дважды. Можете исправить?

2020-03-13 13:35 UTC, kajigor commented on src/Expr.hs
> +pow   = symbol '^' >>= toOperator
Что-то не так

```
λ> runParser parseExpr "1^2"
Success "^2" 
1
```

2020-03-13 13:50 UTC, AlyaNovikova commented on src/Expr.hs
> +            t <- term
Исправила

2020-03-13 13:51 UTC, AlyaNovikova commented on src/Expr.hs
> +pow   = symbol '^' >>= toOperator
Ойййй, там в AST не было возведения в степень :(
Исправила

2020-03-14 19:40 UTC, kajigor commented
ok

2020-03-14 19:40 UTC, closed without merging