Кислицын Андрей HW03
kajigor/fl_2020_spbu_spr pull request #43
Opened 2020-03-12 18:14 UTC by AndreiKingsley

А баги в тестах это пасхалка?

2020-03-14 18:53 UTC, kajigor requested changes

2020-03-14 18:53 UTC, kajigor commented on src/Expr.hs
> +		powPars = symbol '^' >>= toOperator
Что-то не так

```
λ> runParser parseExpr "1^2"
Success "^2" 
1
```

2020-03-14 18:53 UTC, kajigor commented
Баги в тестах это случайность.

2020-03-14 20:12 UTC, AndreiKingsley commented
@kajigor, исправил

2020-03-18 14:14 UTC, kajigor commented
ok

2020-03-18 14:14 UTC, closed without merging