HW03 Павлов Иван
kajigor/fl_2020_spbu_spr pull request #46
Opened 2020-03-12 20:56 UTC by pavlov200912

Почему-то не мержит, может потому что я немного тесты поменял, но я вроде никогда их не ослаблял, только усиливал.

2020-03-14 19:29 UTC, kajigor commented
Наверное, не мержит из-за этого? 
```
<<<<<<< HW03
--АААААА как же долго я искал, почему у меня не заходит тесты длины больше 5 элементов
=======
>>>>>>> HW03
```

2020-03-14 19:31 UTC, kajigor requested changes

2020-03-14 19:31 UTC, kajigor commented on src/Expr.hs
> +pow   = symbol '^' >>= toOperator
Что-то тут не так: 

```
λ> runParser parseExpr "1^4"
Success "^4" 
1
```

2020-03-19 11:20 UTC, pavlov200912 commented
Исправлено!

2020-03-23 10:07 UTC, kajigor commented
ok

2020-03-23 10:07 UTC, closed without merging