HW04 Воронин Илья
kajigor/fl_2020_spbu_spr pull request #48
Opened 2020-03-19 12:48 UTC by ilyavoronin

Я сделал несколько изменений:
1)Числа бывают только с одним унарным минусом и не бывает -0
2) || и && правоассоциативны(вроде везде же так)

2020-03-23 11:50 UTC, kajigor requested changes

2020-03-23 11:50 UTC, kajigor commented on DOCS.md
> +* var a : Type;\
У нас еще и объявлений переменных в абстрактном синтаксисе нет.

2020-03-23 11:50 UTC, kajigor commented on DOCS.md
> +* Идентификаторы состоят из [‘a’ – ‘z’, ‘A’ – ‘Z’, '0' - '9', ‘_’] и еще сколько-то ' в конце(как в хаскеле) и не могут начинаться с цифры
А зачем ограничение, что апострофы только в конце? В Хаскелле `x'123` вполне корректный идентификатор.

2020-03-23 11:50 UTC, kajigor commented on src/Expr.hs
> +      return $ [c] ++ s ++ t;
Нетривиальный способ, но ладно.

2020-03-30 07:34 UTC, closed without merging

2020-04-02 15:34 UTC, ilyavoronin commented on DOCS.md
> +* var a : Type;\
я думал что это не очень важно. В смысле не думал что важно было эти строчки из документации удалять. в новом дз удалю

2020-04-02 15:34 UTC, ilyavoronin commented on DOCS.md
> +* Идентификаторы состоят из [‘a’ – ‘z’, ‘A’ – ‘Z’, '0' - '9', ‘_’] и еще сколько-то ' в конце(как в хаскеле) и не могут начинаться с цифры
я никогда не использовал апострофы по середине. У меня будут только в конце

2020-04-02 15:34 UTC, ilyavoronin commented on src/Expr.hs
> +      return $ [c] ++ s ++ t;
надо было что-то изменить?