HW04 Павлов Иван
kajigor/fl_2020_spbu_spr pull request #50
Opened 2020-03-19 16:41 UTC by pavlov200912

Потратил на haskell 3 часа
Не 30 минут((

2020-03-23 13:36 UTC, kajigor requested changes

2020-03-23 13:36 UTC, kajigor commented on src/Expr.hs
> +            (((:) <$> satisfy (const True) <*>((:[]) <$> (satisfy (const True))) >>= toOperator))
Это что такое вообще?

2020-03-26 15:43 UTC, pavlov200912 commented on src/Expr.hs
> +            (((:) <$> satisfy (const True) <*>((:[]) <$> (satisfy (const True))) >>= toOperator))
Это некрасивый, но рабочий код =)
Эта штука говорит: откуси символ и попробуй скастовать к оператору
неполучилось? откуси два и попробуй, тогда точно получится. 
Вот такая штука.

2020-03-30 07:35 UTC, kajigor commented
ok

2020-03-30 07:35 UTC, closed without merging