Hw04
kajigor/fl_2020_spbu_spr pull request #55
Opened 2020-03-19 19:17 UTC by jeinygroove

2020-03-23 14:04 UTC, kajigor requested changes

2020-03-23 14:04 UTC, kajigor commented on src/Expr.hs
> +parseNum = Parser $ \input -> case input of
Реализуйте это при помощи комбинаторов. Тут уместен `fmap`, например

2020-03-24 11:21 UTC, jeinygroove commented
@kajigor исправила :) (извините, что не быстро прислала исправления, в самолете была)

2020-03-25 09:10 UTC, kajigor commented
ok

2020-03-25 09:10 UTC, closed without merging