Кислицын Андрей HW04
kajigor/fl_2020_spbu_spr pull request #58
Opened 2020-03-19 19:56 UTC by AndreiKingsley

2020-03-23 14:20 UTC, kajigor requested changes

2020-03-23 14:20 UTC, kajigor commented on src/Expr.hs
> +parseNum = Parser $ \input ->
Реализуйте этот парсер без сопоставления с шаблоном, используйте имеющиеся комбинаторы

2020-03-23 14:45 UTC, AndreiKingsley commented on src/Expr.hs
> +parseNum = Parser $ \input ->
@kajigor, сделал!

2020-03-25 09:12 UTC, kajigor commented
ok

2020-03-25 09:12 UTC, closed without merging