HW01
kajigor/fl_2020_spbu_spr pull request #6
Opened 2020-02-23 14:40 UTC by AlyaNovikova

2020-02-24 11:02 UTC, kajigor requested changes

2020-02-24 11:02 UTC, kajigor commented on src/Arith.hs
> +parseLbr (x:xs) | x == '(' = Just ((), xs)
Можно проверку `x == '('` прямо в сопоставление с шаблоном внести: 

```
parseLbr ('(' : xs) -> ...
```

2020-02-24 15:15 UTC, AlyaNovikova commented
исправила parseLbr и parseRbr :)

2020-02-24 15:50 UTC, AlyaNovikova commented on src/Arith.hs
> +parseLbr (x:xs) | x == '(' = Just ((), xs)
> исправила parseLbr и parseRbr :)

2020-02-26 10:47 UTC, kajigor commented
ok

2020-02-26 10:47 UTC, closed without merging