Hw05
kajigor/fl_2020_spbu_spr pull request #66
Opened 2020-03-26 15:55 UTC by jeinygroove

Я не поняла как в таблице в markdown файле написать || (Логическое ИЛИ), поэтому написала OR пока что))

2020-03-27 12:57 UTC, kajigor commented
2: В этой грамматике проблем не возникает, но в общем случае будьте осторожны, удаляя эпсилон-продукции, если к этому моменту стартовый нетерминал остается в правых частях правил. Лучше добавить новый стартовый нетерминал заранее. 
3: ок

2020-03-27 13:00 UTC, kajigor requested changes

2020-03-27 13:00 UTC, kajigor commented on Llang.md
> +Именем переменной может служить любая строка, первым символом которой является либо символ латинского алфавита, либо `_`
даже `_!{}_`?

2020-03-27 13:00 UTC, kajigor commented on Llang.md
> +| `-`| унарный минус | 8| Правоассоциативный |
То есть `-2^2 = 4`?

2020-03-27 13:12 UTC, kajigor commented
Спецификация хорошая, нужно поправить мелочи. 
А палки надо просто экранировать: ` \|\| `

2020-03-27 13:17 UTC, jeinygroove commented on Llang.md
> +Именем переменной может служить любая строка, первым символом которой является либо символ латинского алфавита, либо `_`
ой, неправильно выразилась, сейчас исправлю)

2020-03-27 13:33 UTC, jeinygroove commented on Llang.md
> +| `-`| унарный минус | 8| Правоассоциативный |
По таким приоритетам да, добавила в пример

2020-03-30 07:38 UTC, kajigor commented
ok

2020-03-30 07:38 UTC, closed without merging