HW05 Иван Олейник
kajigor/fl_2020_spbu_spr pull request #67
Opened 2020-03-26 17:04 UTC by ivanoleinik

2020-03-26 18:22 UTC, ivanoleinik commented
потратил примерно 6 часов, время как-то быстро пролетело, наверное потому что придумывать L было интересно :)

2020-03-27 13:05 UTC, kajigor requested changes

2020-03-27 13:05 UTC, kajigor commented on Llang.md
> +  `if`       | `if (expr) ins ins'`      | Если `expr == 0`, то выполняется инструкция `ins1`, а `ins2` игнорируется, иначе наоборот.
нет никаких `ins1` и `ins2`

2020-03-27 13:05 UTC, kajigor commented on Llang.md
> +- Алфавит языка L состоит из символов диапазонов `[a-zA-Z0-9_'./\;]` и `[\t\n\v\f\r ]`.
А скобочки?

2020-03-27 13:06 UTC, kajigor commented
Меня радует, что это было интересное задание :) 

> потратил примерно 6 часов, время как-то быстро пролетело, наверное потому что придумывать L было интересно :)

2020-03-27 13:07 UTC, kajigor commented
2 3 ок. 
Будьте осторожны при удалении эпсилон-правил во время приведения в НФХ, когда у вас стартовый нетерминал находится в правых частях правил. Лучше заранее ввести новый стартовый нетерминал.

2020-03-27 13:08 UTC, kajigor commented
Спецификация хорошая, надо только мелочи поправить

2020-03-27 13:09 UTC, ivanoleinik commented on Llang.md
> +  `if`       | `if (expr) ins ins'`      | Если `expr == 0`, то выполняется инструкция `ins1`, а `ins2` игнорируется, иначе наоборот.
поправил

2020-03-27 13:09 UTC, ivanoleinik commented on Llang.md
> +- Алфавит языка L состоит из символов диапазонов `[a-zA-Z0-9_'./\;]` и `[\t\n\v\f\r ]`.
добавил

2020-03-27 13:12 UTC, kajigor commented
ok

2020-03-27 13:12 UTC, closed without merging