Павлов Иван HW01
kajigor/fl_2020_spbu_spr pull request #7
Opened 2020-02-24 10:38 UTC by pavlov200912

домаха сделана

2020-02-24 11:09 UTC, kajigor requested changes

2020-02-24 11:09 UTC, kajigor commented on src/Arith.hs
> +                          (Num y, "") <- parseNum reversedNumber
Если вы пользуетесь функцией, которая уже парсит число, зачем сначала проверять, правда ли, что префикс строки является числом?

2020-02-24 11:09 UTC, kajigor commented on src/Arith.hs
> +                          (' ':other') <- return $ other
Что? 
Это вы так пробел пропускаете?

2020-02-24 11:09 UTC, kajigor commented on src/Arith.hs
> +                    (tree, "") <- parsePostfix $ reverse input
А можете сделать то же самое, только не разворачивая строку?

2020-02-24 18:17 UTC, pavlov200912 commented on src/Arith.hs
> +                          (Num y, "") <- parseNum reversedNumber
Не понял(
У меня есть 2 разных случая, либо это ещё узел дерева и в начале операция, либо это уже лист с числом внутри. 
Да, я мог использовать вычисления parseNum в монаде Maybe, но тогда все равно писал бы case Nothing или что-то такое, видимо.

2020-02-24 18:19 UTC, pavlov200912 commented on src/Arith.hs
> +                          (' ':other') <- return $ other
Да. 
Тоже немного не понял вопроса, это некрасиво?
У меня есть строка <что-то> + ' ' + (операция)
Операцию я уже откусил и теперь у меня тут обязан стоять пробел.
Я одновременно откусываю его и проверяю строку на корректность, всё же в монаде.

2020-02-24 18:27 UTC, pavlov200912 commented on src/Arith.hs
> +                    (tree, "") <- parsePostfix $ reverse input
Вот тут интересно, конечно. 
Я честно попробовал написать, но у меня не получается. А именно, реализовать мою идею с частичным парсингом поддеревьев при прямом проходе у меня не выходит. 
Приницип был в том, что если я разворачиваю строку, то я могу гарантированно распарсить правое поддерево "пока парситься" и выплюнуть левое в качестве недопаршенной строки. Это происходит, потому что я начинаю парсить с самого верхнего узла (правого поддерева) и спускаюсь вниз.
Если же у меня прямой проход, мне надо как-то подниматься по дереву снизу вверх, это кажется уже не так тривиально. 
Разве можно как-то легко распарсить снизу вверх, используя  String -> Maybe (AST, String)

2020-02-26 10:53 UTC, kajigor commented on src/Arith.hs
> +                          (' ':other') <- return $ other
Суть вопроса в том, что я просто никогда не видела, чтобы так писали, и хотела разобраться, зачем оно надо :) 
`(x, z) <- return y` делает то же самое, что `let (x, z) = y`, но сначала завернет значение в монаду, а потом его оттуда достанет. 
Еще вариант -- воткнуть это действие в верхнеуровневое сопоставление с шаблоном: `parsePostfix (c : ' ' : other') = ...`

2020-02-26 10:58 UTC, kajigor commented on src/Arith.hs
> +                    (tree, "") <- parsePostfix $ reverse input
Можно использовать вспомогательную функцию, использующую вспомогательный стек для уже построенных поддеревьев. Примерно та же идея, что при вычислении значения выражения в постфиксной записи. В принципе, большой разницы нет.

2020-02-26 11:06 UTC, kajigor commented on src/Arith.hs
> +                          (Num y, "") <- parseNum reversedNumber
`parseNum` съедает из строки префикс из подряд идущих цифр после чего преобразует их в `Int`. Не очень понятно, зачем дублировать эту работу вызовом `takeWhile isDigit`. 

В вашем стиле можно написать что-то в духе 
`parsePostfix input | d <- parseNum = d`

2020-02-26 11:07 UTC, kajigor commented on src/Arith.hs
> +                          (Num y, "") <- parseNum reversedNumber
А, или это потому, что у вас число оказывается перевернутым?

2020-02-26 11:10 UTC, kajigor commented on src/Arith.hs
> +                          (Num y, "") <- parseNum reversedNumber
Думаю, если хочется пользоваться идеей с переворачиванием строки, лучше тогда разбить ее по пробелам, перевернуть получившийся список, а дальше пользоваться уже имеющимися парсерами. 

`reverseSubExprs = reverse . words`

2020-02-26 18:25 UTC, pavlov200912 commented on src/Arith.hs
> +                          (Num y, "") <- parseNum reversedNumber
revese . words это очень справедливо
сделал

2020-02-26 18:26 UTC, pavlov200912 commented on src/Arith.hs
> +                          (' ':other') <- return $ other
точно let (x, z) = y в монаду обернет и достанет?
я попробовал, тесты почему-то падали
оставил (x, z) <- return y
так монада явно видна

2020-02-26 18:26 UTC, pavlov200912 commented on src/Arith.hs
> +                    (tree, "") <- parsePostfix $ reverse input
сделал версию со стеком
называется fromPostfixStraight
добавил к ней тестов

2020-02-26 18:26 UTC, pavlov200912 reviewed
@kajigor, исправлено!

2020-02-27 07:02 UTC, kajigor commented on src/Arith.hs
> +                          (' ':other') <- return $ other
`return` оборачивает, `<-` достает. `let` в этом случае лучше. Я в вашем коде локально заменяла этот кусочек кода, все было ок, тесты проходили.

2020-02-27 07:07 UTC, kajigor commented
ok

2020-02-27 07:07 UTC, closed without merging

2020-03-16 14:21 UTC, kajigor commented on src/Arith.hs
> +                          (' ':other') <- return $ other
> точно let (x, z) = y в монаду обернет и достанет?
> я попробовал, тесты почему-то падали
> оставил (x, z) <- return y
> так монада явно видна

Внезапно Нил Митчел написал, зачем может быть нужно делать то, что вы делали: https://neilmitchell.blogspot.com/2020/03/the-pure-pattern.html

Если коротко, то чтобы избегать бесконечных циклов