complete
kajigor/fl_2020_spbu_spr pull request #8
Opened 2020-02-26 14:15 UTC by AndreiKingsley

2020-02-26 14:27 UTC, AndreiKingsley commented
Как пофиксить пробелы в конце? А то некрасивые получились комиты.

2020-02-26 14:29 UTC, kajigor requested changes

2020-02-26 14:29 UTC, kajigor commented on src/Arith.hs
> +fromPostfix' (x:xs) (Just a) | (isOp x) && (length a >= 2) = do
Вот эту проверку длины стека можно было прямо в сопоставление с шаблоном встроить: 

```
fromPostfix' (x:xs) (Just (y:z:stack)) | isOp x = do 
... 
                fromPostfix' xs $ Just (BinOp op z y : stack)
...
```

2020-02-26 14:29 UTC, kajigor commented on src/Arith.hs
> +parseLbr [] = Nothing
Этот случай можно смело удалять, он попадает под вайлдкард на 62 строчке.

2020-02-26 14:29 UTC, kajigor commented on src/Arith.hs
> +parseRbr [] = Nothing
Этот тоже можно удалять

2020-02-26 14:29 UTC, kajigor commented on src/Arith.hs
> +      xs -> Just (Num $ Sum.parseNum xs, rest)) <|> do
О, комбинатор. Хорошо.

2020-02-26 14:34 UTC, kajigor commented
Вообще при коммите можно не коммитить пробелы ([вот тут](https://til.hashrocket.com/posts/696df00135-remove-whitespace-changes-then-git-add-p) какое-то похожее заклинание есть, я его не проверяла). В некоторых GUI-приложеньках для гита были для этого галочки. 

Но вообще мне это не принципиально: тут есть опция смотреть на пулл-реквесты, игнорируя пробелы в конце строк: 
![Screenshot from 2020-02-26 17-28-55](https://user-images.githubusercontent.com/1614576/75354558-3259d500-58be-11ea-83de-f9bf044186fb.png)

2020-02-26 21:55 UTC, AndreiKingsley commented
@kajigor, исправил

2020-02-27 07:10 UTC, kajigor commented
ок

2020-02-27 07:10 UTC, closed without merging