Кислицын Андрей HW06
kajigor/fl_2020_spbu_spr pull request #86
Opened 2020-04-02 20:21 UTC by AndreiKingsley

Сделал хаскель, а вот свой парсер пока нет(.

2020-04-06 13:44 UTC, kajigor commented
`uberExpr` ok

2020-04-07 13:41 UTC, AndreiKingsley commented
@kajigor , парсер для языка сделал!

2020-04-09 09:40 UTC, kajigor commented
Пример из документации не парсится

```
λ> runParser parseL "{#ROBIT#{#ZVYAZATI#@USSR@:$CELKOVIY$$DEVYATICHOK$$DEVYATICHOK$$CELKOVIY$+-$CELKOVIY$$DEVYATICHOK$$POLUSHKA$$POLUSHKA$:}{#KOLI#:@USSR@>$CELKOVIY$$NOL$$NOL$:#TADI#{#ZVYAZATI#@USSR@:CELKOVIY+NOL−NOL:}#PO−INOMU#{#PUSTO#}}}{#PAKUL#:@USSR@:{#NAPISATNABERESTE#:$ZOLOTNICHOK$:}}}"
Failure "Predicate failed"
```

Как с подчеркиваниями вокруг унарного минуса, так и без них.

2020-04-09 09:40 UTC, kajigor commented
Из документации непонятно, когда нужно ставить фигурные скобки, а когда нет.

2020-04-09 09:41 UTC, kajigor requested changes

2020-04-09 09:41 UTC, kajigor commented on src/LLang.hs
> +  | Empty
Для этого придумали `Seq []`

2020-04-09 10:01 UTC, AndreiKingsley commented on src/LLang.hs
> +  | Empty
Не очень понял что имеется в виду? То что Empty = Seq[] ?
Или то что Seq[Empty] = Seq[]? Если что, второе не верно  в моём языке, т.к. валидна запись Seq[Empty, Empty, Empty], которая не должны быть равна Seq[].

2020-04-09 10:20 UTC, AndreiKingsley commented on src/LLang.hs
> +  | Empty
Ну вот например мой пример из документации из предыдущего коммента, там после else ничего нет. Я считаю, что это Empty блок а не пустая последовательность Seq [].

2020-04-09 10:44 UTC, AndreiKingsley commented
Добавил пример из документации в тесты, всё работает(удалили их из документации примеры, т.к.  латех  не даёт нормально залить строчку, там проблемы какие-то с кодировкой)
Про унарный минус я удалил, уточнил описание блока.

2020-04-09 11:27 UTC, kajigor commented on src/LLang.hs
> +  | Empty
Не нужна `Empty`, потому что пустая последовательность это `Seq []`. Пустой блок вполне выражается как блок с нулем инструкций. Менять абстрактный синтаксис без достаточно значимой для этого причины нельзя.

2020-04-09 11:38 UTC, kajigor commented
Йеее, даже фибоначчи распарсились 
```
test "{#ROBIT#{#CHITATSBERESTI#@s@}{#KOLI#:@s@==$CELKOVIY$||@s@==$POLUSHKA$:#TADI#{#NAPISATNABERESTU#:$CELKOVIY$:}#PO-INOMU#{#ROBIT#{#ZVYAZATI#@rr@:$POLUSHKA$:}{#ZVYAZATI#@rus@:$CELKOVIY$:}{#ZVYAZATI#@ssss@:$CELKOVIY$:}{#PAKUL#:@rr@<@s@:{#ROBIT#{#ZVYAZATI#@uuuu@:@rus@+@ssss@:}{#ZVYAZATI#@ssss@:@rus@:}{#ZVYAZATI#@rus@:@uuuu@:}{#ZVYAZATI#@rr@:@rr@+$CELKOVIY$:}}}{#NAPISATNABERESTU#:@rus@:}}}}"
```

ok

2020-04-09 11:38 UTC, closed without merging